profile:
  name: pdf

format:
  pdf:
    documentclass: article
    toc: true
    toc-depth: 2
    number-sections: true
    colorlinks: true
    papersize: a4
    geometry:
      - margin=2.5cm
    keep-tex: false
    cite-method: biblatex
